In [1]:
import sys
sys.path.append('../../dataloaders/3W')
sys.path.append('../../../3W')
import os
os.environ['path3W'] = '../../../'
import numpy as np
import pandas as pd

In [2]:
from loader import Loader3W
import importlib
importlib.reload(sys.modules['loader'])
import toolkit
importlib.reload(sys.modules['toolkit'])
ld = Loader3W()

In [ ]:
#ld.get_ids_from_wells_with_event_type([8])
#ld.load_stats()
#ld.extract_stats(['ABER-CKP', 'P-ANULAR', 'P-PDG','P-TPT','T-MON-CKP','T-PDG','T-TPT'])

In [ ]:
#ld.save_stats()

In [3]:
ld.load_stats()
dg = ld.preprocess()

In [4]:
from diffusion.ts_diffusion2 import TSDiffusion
importlib.reload(sys.modules['diffusion.ts_diffusion2'])
ts_diffusion = TSDiffusion(
    in_channels=17,
    latent_dim=256,
    model_dim=256,
    static_dim=7,
    hidden_dim=1024,
    num_steps=1000
    )


In [ ]:
import torch
ts_diffusion = ts_diffusion.to(device=torch.device('cuda'))
ts_diffusion.train3W(
    window_size=15,
    batch_size=5000,
    epochs=5
)

Starting epoch 1/5 - dataset 1/9 - Partial Validation Loss: inf
Ep 1: L1=94.07 L2=1.00 L3=0.10 L4=0.52
Ep 1: L1=16.34 L2=1.00 L3=0.11 L4=0.21
Ep 1: L1=-12.04 L2=1.00 L3=0.15 L4=0.03
Ep 1: L1=-25.86 L2=1.00 L3=0.14 L4=0.03
Ep 1: L1=-27.92 L2=1.00 L3=0.13 L4=0.04
Starting epoch 1/5 - dataset 2/9 - Partial Validation Loss: 0.999273
Ep 1: L1=-17.98 L2=1.00 L3=0.14 L4=0.04
Ep 1: L1=-29.85 L2=1.00 L3=0.13 L4=0.02
Ep 1: L1=-32.21 L2=1.00 L3=0.13 L4=0.01
Ep 1: L1=-32.51 L2=1.00 L3=0.13 L4=0.01
Ep 1: L1=-33.27 L2=1.00 L3=0.10 L4=0.00
Starting epoch 1/5 - dataset 3/9 - Partial Validation Loss: 0.999856
Ep 1: L1=-21.00 L2=1.00 L3=0.10 L4=0.00
Ep 1: L1=-31.11 L2=1.00 L3=0.14 L4=0.03
Ep 1: L1=-32.53 L2=1.00 L3=0.12 L4=0.01
Ep 1: L1=-33.19 L2=1.00 L3=0.10 L4=0.00
Ep 1: L1=-33.31 L2=1.00 L3=0.13 L4=0.00
Starting epoch 1/5 - dataset 4/9 - Partial Validation Loss: 0.999823
Ep 1: L1=-29.83 L2=1.00 L3=0.13 L4=0.00
Ep 1: L1=-33.08 L2=1.00 L3=0.13 L4=0.01
Ep 1: L1=-33.76 L2=1.00 L3=0.06 L4=0.00
Ep 1: L1=-3

In [ ]:
'''ts_diffusion = ts_diffusion.load('ts_diffusion_3w_ep11.pt',in_channels=17,
    latent_dim=256,
    model_dim=256,
    static_dim=7,
    hidden_dim=1024,
    num_steps=1000)'''

In [53]:
ts_diffusion.test_sampler()

{'ABER-CKP': (array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14.]),
  array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan]),
  array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14.], dtype=float32),
  array([0.00067464, 0.00067464, 0.00067464, 0.00067464, 0.00067464,
         0.00067464, 0.00067464, 0.00067464, 0.00067464, 0.00067464,
         0.00067464, 0.00067464, 0.00067464, 0.00067464, 0.00067464],
        dtype=float32)),
 'P-ANULAR': (array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14.]),
  array([0.71670581, 0.71674489, 0.71678511, 0.71682419, 0.71686442,
         0.7169035 , 0.71694373, 0.71698281, 0.71702189, 0.71706211,
         0.71710119, 0.71714142, 0.7171805 , 0.71722073, 0.71725981]),
  array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14.], dtype=float32),
  array([0.00035302, 0.000353