In [1]:
import sys
sys.path.append('../../dataloaders/3W')
sys.path.append('../../../3W')
import os
os.environ['path3W'] = '../../../'
import numpy as np
import pandas as pd

In [2]:
from loader import Loader3W
import importlib
importlib.reload(sys.modules['loader'])
import toolkit
importlib.reload(sys.modules['toolkit'])
ld = Loader3W()

In [ ]:
#ld.get_ids_from_wells_with_event_type([8])
#ld.load_stats()
#ld.extract_stats(['ABER-CKP', 'P-ANULAR', 'P-PDG','P-TPT','T-MON-CKP','T-PDG','T-TPT'])

In [ ]:
#ld.save_stats()

In [3]:
ld.load_stats()
dg = ld.preprocess()

In [4]:
from diffusion.ts_diffusion2 import TSDiffusion
importlib.reload(sys.modules['diffusion.ts_diffusion2'])
ts_diffusion = TSDiffusion(
    in_channels=17,
    latent_dim=256,
    model_dim=256,
    static_dim=7,
    hidden_dim=1024,
    num_steps=1000
    )


In [6]:
import torch
#ts_diffusion = ts_diffusion.to(device=torch.device('cuda'))
ts_diffusion.train3W(
    window_size=15,
    batch_size=5000,
    epochs=5
)

Starting epoch 1/5 - dataset 1/9 - Partial Validation Loss: 0.678147
Ep 1: L1=-32.82 L2=0.72 L3=0.13 L4=0.00
Ep 1: L1=-33.45 L2=0.68 L3=0.14 L4=0.00
Ep 1: L1=-33.72 L2=0.66 L3=0.11 L4=0.00
Ep 1: L1=-33.96 L2=0.67 L3=0.07 L4=0.00
Ep 1: L1=-34.05 L2=0.66 L3=0.06 L4=0.00
Starting epoch 1/5 - dataset 2/9 - Partial Validation Loss: 0.694050
Ep 1: L1=-33.44 L2=0.74 L3=0.12 L4=0.00
Ep 1: L1=-33.93 L2=0.67 L3=0.06 L4=0.00
Ep 1: L1=-34.00 L2=0.64 L3=0.07 L4=0.00
Ep 1: L1=-33.98 L2=0.62 L3=0.08 L4=0.00
Ep 1: L1=-33.87 L2=0.62 L3=0.08 L4=0.00
Starting epoch 1/5 - dataset 3/9 - Partial Validation Loss: 0.644552
Ep 1: L1=-33.33 L2=0.66 L3=0.16 L4=0.00
Ep 1: L1=-33.40 L2=0.63 L3=0.13 L4=0.00
Ep 1: L1=-33.81 L2=0.64 L3=0.08 L4=0.00
Ep 1: L1=-33.69 L2=0.64 L3=0.06 L4=0.00
Ep 1: L1=-33.82 L2=0.63 L3=0.07 L4=0.00
Starting epoch 1/5 - dataset 4/9 - Partial Validation Loss: 0.654035
Ep 1: L1=-32.85 L2=0.64 L3=0.12 L4=0.00
Ep 1: L1=-33.70 L2=0.64 L3=0.07 L4=0.00
Ep 1: L1=-33.92 L2=0.63 L3=0.07 L4=0.00
Ep 1

In [ ]:
ts_diffusion = ts_diffusion.load('ts_diffusion_3w_ep11.pt',in_channels=17,
    latent_dim=256,
    model_dim=256,
    static_dim=7,
    hidden_dim=1024,
    num_steps=1000)
#ts_diffusion.save('ts_diffusion_3w_ep10.pt')

In [7]:
ts_diffusion.test_sampler()

{'ABER-CKP': (array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14.]),
  array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan]),
  array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14.], dtype=float32),
  array([  47287.49 , 1296520.4  , 2000142.1  ,  -53725.73 , 1843861.2  ,
         -313047.38 , 1905783.2  ,   56158.047, 1867106.6  , -239990.67 ,
         1972567.5  , -212282.23 , 1899827.5  ,  -30352.9  , 1931383.8  ],
        dtype=float32)),
 'P-ANULAR': (array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14.]),
  array([0.71670581, 0.71674489, 0.71678511, 0.71682419, 0.71686442,
         0.7169035 , 0.71694373, 0.71698281, 0.71702189, 0.71706211,
         0.71710119, 0.71714142, 0.7171805 , 0.71722073, 0.71725981]),
  array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14.], dtype=float32),
  array([-3252