In [1]:
import sys
sys.path.append('../../dataloaders/3W')
sys.path.append('../../../3W')
import os
os.environ['path3W'] = '../../../'
import numpy as np
import pandas as pd

In [2]:
from loader import Loader3W
import importlib
importlib.reload(sys.modules['loader'])
import toolkit
importlib.reload(sys.modules['toolkit'])
ld = Loader3W()

In [ ]:
#ld.get_ids_from_wells_with_event_type([8])
#ld.load_stats()
#ld.extract_stats(['ABER-CKP', 'P-ANULAR', 'P-PDG','P-TPT','T-MON-CKP','T-PDG','T-TPT'])

In [ ]:
#ld.save_stats()

In [3]:
ld.load_stats()
dg = ld.preprocess()

In [46]:
from diffusion.ts_diffusion2 import TSDiffusion
importlib.reload(sys.modules['diffusion.ts_diffusion2'])
ts_diffusion = TSDiffusion(
    in_channels=17,
    latent_dim=256,
    model_dim=256,
    static_dim=7,
    hidden_dim=1024,
    num_steps=1000
    )


In [42]:
import torch
#ts_diffusion = ts_diffusion.to(device=torch.device('cuda'))
ts_diffusion.train3W(
    window_size=15,
    batch_size=5000,
    epochs=5
)

Starting epoch 1/5 - dataset 1/9 - Partial Validation Loss: inf
Ep 1: L1=-32.32 L2=0.42 L3=0.12 L4=0.00
Ep 1: L1=-33.02 L2=0.36 L3=0.13 L4=0.00
Ep 1: L1=-33.63 L2=0.35 L3=0.12 L4=0.00
Ep 1: L1=-33.83 L2=0.33 L3=0.06 L4=0.00
Ep 1: L1=-33.99 L2=0.33 L3=0.04 L4=0.00
Starting epoch 1/5 - dataset 2/9 - Partial Validation Loss: 0.379715
Ep 1: L1=-33.30 L2=0.41 L3=0.13 L4=0.00
Ep 1: L1=-33.82 L2=0.33 L3=0.06 L4=0.00
Ep 1: L1=-33.85 L2=0.34 L3=0.07 L4=0.00
Ep 1: L1=-33.93 L2=0.32 L3=0.08 L4=0.00
Ep 1: L1=-33.79 L2=0.33 L3=0.08 L4=0.00
Starting epoch 1/5 - dataset 3/9 - Partial Validation Loss: 0.363794
Ep 1: L1=-32.97 L2=0.41 L3=0.14 L4=0.00
Ep 1: L1=-33.20 L2=0.36 L3=0.12 L4=0.00
Ep 1: L1=-33.85 L2=0.33 L3=0.08 L4=0.00
Ep 1: L1=-33.94 L2=0.31 L3=0.06 L4=0.00
Ep 1: L1=-34.07 L2=0.30 L3=0.06 L4=0.00
Starting epoch 1/5 - dataset 4/9 - Partial Validation Loss: 0.345599
Ep 1: L1=-33.47 L2=0.40 L3=0.12 L4=0.00
Ep 1: L1=-33.87 L2=0.34 L3=0.05 L4=0.00
Ep 1: L1=-33.93 L2=0.33 L3=0.05 L4=0.00
Ep 1: L1=

In [ ]:
ts_diffusion = ts_diffusion.load('ts_diffusion_3w_ep15.pt',in_channels=17,
    latent_dim=256,
    model_dim=256,
    static_dim=7,
    hidden_dim=1024,
    num_steps=1000)
#ts_diffusion.save('ts_diffusion_3w_ep15.pt')

In [44]:
ts_diffusion.test_sampler()

{'ABER-CKP': (array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14.]),
  array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan]),
  array([0.        , 0.07142857, 0.14285715, 0.21428572, 0.2857143 ,
         0.35714287, 0.42857143, 0.5       , 0.5714286 , 0.64285713,
         0.71428573, 0.78571427, 0.85714287, 0.9285714 , 1.        ],
        dtype=float32),
  array([-11.972396 , -12.704782 ,  -4.85997  ,  -6.6126704,  -2.311146 ,
          -6.139841 ,  -9.164581 , -14.412748 , -16.234858 ,  -3.80114  ,
         -11.299345 ,  -3.3720806, -12.966477 , -12.334042 ,  -9.537888 ],
        dtype=float32)),
 'P-ANULAR': (array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14.]),
  array([0.71670581, 0.71674489, 0.71678511, 0.71682419, 0.71686442,
         0.7169035 , 0.71694373, 0.71698281, 0.71702189, 0.71706211,
         0.71710119, 0.71714142, 0.7171805 , 0.71722073, 0.71725981]),
  