In [1]:
import tensorflow as tf

2025-07-02 22:41:44.816032: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-02 22:41:44.836141: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1751496104.851668   85471 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1751496104.856091   85471 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1751496104.865947   85471 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
filenames = [
    'data/fake_rings.tfrecord'
]
raw_dataset = tf.data.TFRecordDataset(filenames)

2025-07-02 22:41:46.386171: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [5]:
N_RINGS = 100
parse_schema = {
    'id': tf.io.FixedLenFeature([], tf.int64),
    'et': tf.io.FixedLenFeature([], tf.float32),
    'eta': tf.io.FixedLenFeature([], tf.float32),
    'avgmu': tf.io.FixedLenFeature([], tf.float32),
    'label': tf.io.FixedLenFeature([], tf.int64),
}
for i in range(N_RINGS):
    parse_schema[f'ring_{i}'] = tf.io.FixedLenFeature([], tf.float32)

def parse_example(serialized_string):
    return tf.io.parse_single_example(
        serialized_string,
        parse_schema
    )


In [6]:
parsed_dataset = raw_dataset.map(parse_example)

In [8]:
for i, example in enumerate(parsed_dataset.take(3)):
    print(f"Example {i}: {type(example)}")
    print(example)

Example 0: <class 'dict'>
{'avgmu': <tf.Tensor: shape=(), dtype=float32, numpy=0.4479549825191498>, 'et': <tf.Tensor: shape=(), dtype=float32, numpy=-0.2170238345861435>, 'eta': <tf.Tensor: shape=(), dtype=float32, numpy=0.7830294966697693>, 'id': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'ring_0': <tf.Tensor: shape=(), dtype=float32, numpy=1.0046939849853516>, 'ring_1': <tf.Tensor: shape=(), dtype=float32, numpy=0.8078832030296326>, 'ring_10': <tf.Tensor: shape=(), dtype=float32, numpy=1.5180864334106445>, 'ring_11': <tf.Tensor: shape=(), dtype=float32, numpy=-2.1276819705963135>, 'ring_12': <tf.Tensor: shape=(), dtype=float32, numpy=-0.36538341641426086>, 'ring_13': <tf.Tensor: shape=(), dtype=float32, numpy=-1.067672610282898>, 'ring_14': <tf.Tensor: shape=(), dtype=float32, numpy=-1.8080602884292603>, 'ring_15': <tf.Tensor: shape=(), dtype=float32, numpy=-0.4633035957813263>, 'ring_16': <tf.Tensor: shape=(), dtype=float32, nu

2025-07-02 22:43:07.642637: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
